# Generated by Django 2.2.3 on 2019-11-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(max_length=50)),
                ('d_type', models.CharField(max_length=50)),
                ('visible', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('order', models.IntegerField()),
                ('max_length', models.IntegerField()),
                ('form_id', models.ForeignKey(on_delete='CASCADE', to='main.Form')),
            ],
        ),
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_content', models.CharField(max_length=100)),
                ('opt_type', models.CharField(max_length=50)),
                ('opt_order', models.IntegerField()),
                ('q_id', models.ForeignKey(on_delete='CASCADE', to='main.question')),
            ],
        ),
    ]
