# Generated by Django 2.2.3 on 2019-11-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(max_length=50)),
                ('d_type', models.CharField(max_length=50)),
                ('options', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('choices', models.TextField()),
            ],
        ),
    ]
